### ISSUE TITLE
Remove hardcoded credentials from the page object to the proprties

### ISSUE THREAD

**Issue by archick12** [archick12/qa_auto_5_initial#10]

**Comment by archick12** [comment]
![screen shot 2018-01-17 at 5 38 40 pm](https://user-images.githubusercontent.com/3301317/35051196-5734e5a6-fbad-11e7-9aa1-7c2274f6d2fc.png)

**Comment by spektorius** [comment]
created [issue#10](https://github.com/archick12/qa_auto_5_initial/tree/issue%2310) branch with solution
